# Pre-commit configuration for DocxMD Converter
# Tools: black (formatter), isort (imports), flake8 (linter), mypy (type checker)
repos:
  # Black - Python code formatter
  - repo: https://github.com/psf/black
    rev: 24.4.2  # Updated to latest stable
    hooks:
      - id: black
        language_version: python3.11
        args: ["--line-length=88"]

  # isort - Import statement organizer
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black", "--line-length=88"]

  # flake8 - Python linter
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0  # Updated to latest stable
    hooks:
      - id: flake8
        args: [
          "--max-line-length=88",
          "--extend-ignore=E203,W503,E501,D100,D101,D102,D103,D104,D105,D106,D107,D200,D205,D400,D401,B007"
        ]
        additional_dependencies: [flake8-docstrings, flake8-bugbear]

  # mypy - Static type checker (disabled for v3.0.0 release)
  # TODO: Re-enable after improving type annotations
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.10.0
  #   hooks:
  #     - id: mypy

  # Additional quality checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: ^docs/
      - id: end-of-file-fixer
        exclude: ^docs/
      - id: check-yaml
        exclude: ^docs/
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=1000']
